#!/bin/sh

mkdir -p opk
cp ./data/icon.png opk/icon.png
cp ./data/pico8_font.png opk/pico8_font.png
cp ./retro8.elf opk/retro8.elf
cp ./api.lua opk/api.lua
cp ./LICENSE opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Retro8
Comment=PICO-8 Emulator (port gameblabla)
Exec=retro8.elf %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=true
X-OD-Filter=.png,.p8' > opk/default."$1".desktop

mksquashfs ./opk retro8_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
